### ISSUE TITLE
Furnaces and Crafting Tables

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Wolfgange3311999/Mine-DS#13]
```
Make furnaces and crafting tables functional. When near one and crafting, more 
options appear in crafting menu.
```

Original issue reported on code.google.com by `Matthew3...@gmail.com` on 16 Dec 2014 at 2:21

**Comment by Wolfgange3311999** [comment]
Furnaces have been implemented. Only crafting tables are left.

**Comment by CoolAs** [comment]
This has been implemented.
