### ISSUE TITLE
Punch animation glitch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Wolfgange3311999/Mine-DS#31]
```
The first time the player taps the screen in a game session, the first frame of 
the punch animation is transparent.
```

Original issue reported on code.google.com by `Matthew3...@gmail.com` on 28 Feb 2015 at 10:16

**Comment by CoolAs** [comment]
Fixed in commit https://github.com/Wolfgange3311999/Mine-DS/commit/19107f184801adaf9e4823d9b845653c77713627

**Comment by Wolfgange3311999** [comment]
Reopening since the bug still occurs (At least on DeSmuME).
