### ISSUE TITLE
World transfers are slow with many mobs

### ISSUE THREAD

**Issue by Wolfgange3311999** [Wolfgange3311999/Mine-DS#33]
Ideas:
-Make Wifi Updates for mobs slower during a world download.
  (How do we know if somebody quits during a download?)
-Kill all non human mobs when a block request is recieved.
-Don't take notice of mob updates on the client when downloading the world[/s]
-We had other issues with many mobs, you can only spawn five at the moment which fixes the issue. (Anyway five mobs are extremely hard to kill without dying)

**Comment by CoolAs** [comment]
Multiplayer is not enabled at the moment, and when it is enabled, it will be reprogrammed.
No longer an issue.
