### ISSUE TITLE
Controls do not work on Emulators (Not tested on hardware)

### ISSUE THREAD

**Issue by CoolAs** [Wolfgange3311999/Mine-DS#34]
The controls of the player in latest commit are not initialised properly, in the controls menu "Error" is displayed for every control.

The controls do not work as they should. Pressing Left will move the player right, and make the player jump repeatedly.

Tested in DeSmuME on Linux.

**Comment by CoolAs** [comment]
Note files.cpp:102 (Probably not the cause due to the fact this occured on emulator)

fread(controls, sizeof (*controls), 1, fp);

You can not fread a class, because the vtable, which contains the pointers to class functions will not be the same between versions, causing the program to execute unknown code.

**Comment by Wolfgange3311999** [comment]
Hmmm, I am not able to reproduce this bug. What emulator are you using? I'm using No$Zoomer and DesMuMe (on Windows at the moment). Make sure this is still happening after your commit fixing the blockUpdate array.

And along with the config saving vtable issue like you mentioned, the config should be a text file to allow editing outside of MineDS. I'm fixing this right now.

**Comment by CoolAs** [comment]
After the memory corruption commit this should be fixed in emulators.
Loading a config from a different version however will probably crash the game, and that should be fixed.

**Comment by CoolAs** [comment]
The config is now saved in text mode, eliminating this issue.
Fixed in [this commit](http://github.com/Wolfgange3311999/Mine-DS/commit/a9349ef72e90dbb874c56df58e6dda77d9d422f9)
