### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by Wolfgange3311999** [Wolfgange3311999/Mine-DS#37]
Add translations.

**Comment by CoolAs** [comment]
This is a long term goal, should be done after this current release, and multi player.

**Comment by Wolfgange3311999** [comment]
What should the next major release be?  0.3.0? If so, I can make that the
next milestone (and keep this assigned to milestone-future).

**Comment by CoolAs** [comment]
The next major release should be 0.2.0. The next release should have WiFi multiplayer, then we can work on other things. The localizations will also rely on compoglot getting to a usable state.

**Comment by Wolfgange3311999** [comment]
Wait, I thought we are releasing version 0.2.0 soon without multiplayer. We
are at quite a stable point, as long as multiplayer is removed.

**Comment by CoolAs** [comment]
Next release should be 0.2.0, with multiplayer removed, itemMobs fixed and the physics engine fixed.
0.3.0 should be with multiplayer and whatever we have done before then.
0.4.0 should have localizations
From there we should start adding things that minecraft has, but this clone doesn't (Furnace, caves, dungeons etc.)
1.0.0 should be the final major release - where we have implemented most of the features from minecraft.

**Comment by CoolAs** [comment]
Is progress :smiley:

**Comment by CoolAs** [comment]
Most of this is now done, we just need a language selector in hte game settings.

**Comment by CoolAs** [comment]
This issue has been resolved, and is implemented in the v0.4.0 release.
