### ISSUE TITLE
Inventory items do not display after long gameplay

### ISSUE THREAD

**Issue by Wolfgange3311999** [Wolfgange3311999/Mine-DS#51]
After playing for a while, certain item graphics within the inventory will not be displayed. Instead, only their quantities are shown.

**Comment by CoolAs** [comment]
This may be fixed with the new sprite ID handling. 
If the graphic sprites were created, and not unloaded, eventually all the sprite IDs would have been used up, causing future item graphics not to display. Assuming that this was the cause, this bug should no longer appear. Playtesting is required.

**Comment by Wolfgange3311999** [comment]
Assuming fixed.
